package lt.mybatis.model;

import lombok.Getter;
import lombok.Setter;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    private Integer id;
    @Getter
    @Setter
    private Student student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.NAME
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.STUDENT_ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.NAME
     *
     * @return the value of PUBLIC.CAR.NAME
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.NAME
     *
     * @param name the value for PUBLIC.CAR.NAME
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.STUDENT_ID
     *
     * @return the value of PUBLIC.CAR.STUDENT_ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.STUDENT_ID
     *
     * @param studentId the value for PUBLIC.CAR.STUDENT_ID
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}