package lt.mybatis.dao;

import java.util.List;
import lt.mybatis.model.StudentCourse;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Mon May 03 21:30:09 GST 2021
     */
    List<StudentCourse> selectAll();
}